# Generated by Django 3.1.8 on 2021-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0002_auto_20210611_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
